### ISSUE TITLE
Traits mentioned in the docs not shown in the crate root

### ISSUE THREAD

**Issue by WhyNotHugo** [NLnetLabs/octseq#37]
The docs mention:

> These traits are all defined – and explained en detail – in the [traits] module. They are, however, all re-exported here at the crate root.

Note that the `[traits]` link is not linkified, since there is no member with this name. Additionally, there are no traits listed in the root module:

![image](https://github.com/NLnetLabs/octseq/assets/730811/42b8c8a9-54f2-4af8-a079-217930d1615a)

If you want to re-export traits and have them show up in the documentation for the root module, you need to explicitly include `pub use self::mod::trait`. Using wildcards won't document them as expected.

**Comment by partim** [comment]
Thank you for the report and sorry for the late reply. Looks like that doc string is a wee bit outdated.

As for the wildcard re-exports, they really shouldn’t be there: Only the main types and traits from every module should be re-exported. I’ll make a PR to fix that.
